name: workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'          
          distribution: 'zulu'     

      - name: Make gradlew executable
        run: chmod +x ./KIIISeptember/KIIISeptember/gradlew 

      - name: Build with Gradle
        shell: bash
        run: |
          cd ./KIIISeptember/KIIISeptember
          ./gradlew build --info

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: List ./KIIISeptember
        run: ls -la ./KIIISeptember
        
      - name: List ./KIIISeptember/KIIISeptember
        run: ls -la ./KIIISeptember/KIIISeptember

      - name: List ./KIIISeptember/KIIISeptember/build
        run: ls -la ./KIIISeptember/KIIISeptember/build

      - name: List build/libs directory
        run: ls -la ./KIIISeptember/KIIISeptember/build/libs

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: "./KIIISeptember/KIIISeptember"
          push: true
          tags: petarmladenovski/kiii-september:latest
